before:
  hooks:
    - go mod download
builds:
- main: ./cmd/tinygeoip/main.go
  env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - freebsd
    - windows
  ignore:
    - goos: darwin
      goarch: 386
archive:
  replacements:
    darwin: macOS
    386: i386
    amd64: x64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^trivial:'
    - '^release:'
